### ISSUE TITLE
better audio normalization

### ISSUE THREAD

**Issue by siggi1984** [OuterTune/OuterTune#76]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Could you implement the audio normalization from ViMusic/Vitune? As far as I know, Innertune has this since the last update and it is honestly better.

### Why do you want this feature?

For better music enjoyment.

**Comment by mikooomich** [comment]
Iirc that behaves like a compressor rather than normalization (normalization applies a uniform gain), and compression murders dynamic range as a result. Useful feature, and an almost no-brainer for speech, but in the context of music it feels out of place. Not sure if it makes sense for a music player

**Comment by siggi1984** [comment]
> Iirc that behaves like a compressor rather than normalization (normalization applies a uniform gain), and compression murders dynamic range as a result. Useful feature, and an almost no-brainer for speech, but in the context of music it feels out of place. Not sure if it makes sense for a music player

Okay, I personally didn't have that feeling but I'm not an expert and I probably don't have such a good ear. Anyway, it was just a request from me and in the end the developer decides what he implements and what he doesn't...

Thank you for the great app.

**Comment by gechoto** [comment]
> Iirc that behaves like a compressor rather than normalization

correct


> Okay, I personally didn't have that feeling

I personally had that feeling and measured it.
Already reported it to InnerTune & ViTune.

You can see it visualized in these issues (scroll down a bit):
InnerTune: https://github.com/z-huang/InnerTune/issues/1526
ViTune: https://github.com/25huizengek1/ViTune/issues/444

The dev of InnerTune already said he will revert it:
https://github.com/z-huang/InnerTune/issues/1526#issuecomment-2366810995


> Useful feature, and an almost no-brainer for speech

Well YTM also has podcasts and audio books so it might be cool to have it as a separate option besides normalization.
Although not sure how often this is really needed since many already compress their audio before upload.

**Comment by 1305-bit** [comment]
I facing that when ever I play song it show me this the returned video is doesn't match the requested one fix this problem bro
